- include_tasks: '{{ common }}/check_for_binary.yml'
  vars:
    binary: /usr/bin/sudo

- name: /etc/sudoers.d/wheel_group
  copy:
    dest: /etc/sudoers.d/wheel_group
    owner: root
    group: root
    mode: 0600
    content: |
      %wheel ALL = NOPASSWD: /sbin/poweroff, /sbin/reboot
      %wheel ALL = NOPASSWD: /usr/bin/sshuttle
