#!/usr/bin/env ansible-playbook

- name: Apply initial configuration for stage4.
  gather_facts: true
  connection: local
  hosts: localhost
  vars:
    target_cpu: x86-64
    # Common flags between Skylake and Mattise
    cpu_flags_x86: "aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3"
  roles:

  - role: portage
    vars:
      ccache: false
