- name: moar-network-setup
  tags: [moar-network-setup]
  block:
  - name: moar-network-setup.start
    notify: apply moar-network-setup.start
    template:
      src: etc_local.d_moar-network-setup.start.j2
      dest: /etc/local.d/moar-network-setup.start
      owner: root
      group: root
      mode: 0700
  
