- name: restart connman
  when: skip_handlers is not defined
  service:
    name: connman
    state: restarted

- name: reload dbus
  when: skip_handlers is not defined
  service:
    name: dbus
    state: reloaded
