- name: unscd
  tags: [unscd]
  block:
  - set_fact:
      dns_positive_ttl: 10800
      dns_negative_ttl: 5
      dns_cache_size: 1049
  
  - name: nscd.conf
    notify: restart unscd
    template:
      src: etc_nscd.conf.j2
      dest: /etc/nscd.conf
      owner: root
      group: root
      mode: 0644
  
  - name: autostart unscd on boot
    service:
      name: unscd
      runlevel: default
      enabled: true
