- name: resolve_dns_via_localhost
  tags: [resolve_dns_via_localhost]
  block:
  - name: set resolve.conf to 127.0.0.1 with immutable bit
    copy:
      dest: /etc/resolv.conf
      content: "nameserver 127.0.0.1{{'\n'}}"
      attributes: +i
      owner: root
      group: root
      mode: 0644
