- name: Disable udev predictable interface names.
  notify: reload udev rules
  copy:
    dest: /etc/udev/rules.d/80-net-name-slot.rules
    content: "# This file only masks content of /lib/udev/rules.d/80-net-name-slot.rules"
    owner: root
    group: root
    mode: 0644

- name: Disable LVM auto assembly
  notify: reload udev rules
  copy:
    dest: /etc/udev/rules.d/69-dm-lvm-metad.rules
    content: "# This file only masks content of /lib/udev/rules.d/69-dm-lvm-metad.rules"
    owner: root
    group: root
    mode: 0644

- name: Set block devices readahead to 1M
  notify:
  - reload udev rules
  - apply udev storage rules
  copy:
    dest: /etc/udev/rules.d/80-storage-readahead.rules
    src: etc_udev_rules.d_80-storage-readahead.rules
    owner: root
    group: root
    mode: 0644
