- name: Disable udev predictable interface names.
  copy:
    dest: /etc/udev/rules.d/80-net-name-slot.rules
    content: "# This file only masks content of /lib/udev/rules.d/80-net-name-slot.rules"
    owner: root
    group: root
    mode: 0644
