- name: ensure ~/.config exist
  file:
    path: '{{ user_home_dir }}/.config'
    state: directory
    mode: 0700
    owner: '{{ user }}'
    group: '{{ user_group_id }}'

- name: dunstrc deployment
  copy:
    src: DOTconfig_dunstrc
    dest: '{{ user_home_dir }}/.config/dunstrc'
    owner: '{{ user }}'
    group: '{{ user_group_id }}'
    mode: 0600
