- assert:
    that:
    - user is defined

- name: query for home dir of user
  getent:
    database: passwd
    key: '{{ user }}'

- name: set user_home_dir and user_group variables
  set_fact:
    user_home_dir: '{{ getent_passwd[user][4] }}'
    user_group_id: '{{ getent_passwd[user][2] }}'

- assert:
    that:
    - user_home_dir != ""
    - user_group_id != ''

- debug:
    msg:
      - 'user: {{ user }}'
      - 'group_id: {{ user_group_id }}'
      - 'home dir: {{ user_home_dir }}'

# Create ~/.config and ~/.local/share regardless of passed arguments.
- name: ~/.config directory
  file:
    path: '{{ user_home_dir }}/.config'
    state: directory
    mode: 0700
    owner: '{{ user }}'
    group: '{{ user_group_id }}'

- name: ~/.local directory
  file:
    path: '{{ user_home_dir }}/.local'
    state: directory
    mode: 0700
    owner: '{{ user }}'
    group: '{{ user_group_id }}'

- name: ~/.local/share directory
  file:
    path: '{{ user_home_dir }}/.local/share'
    state: directory
    mode: 0700
    owner: '{{ user }}'
    group: '{{ user_group_id }}'

- include_tasks: '{{ config_name }}.yml'
  with_items: '{{ deploy }}'
  loop_control:
    loop_var: config_name
