# todo: add rest of QT4/5 configuration here.

- name: ensure ~/.config exist
  file:
    path: '{{ user_home_dir }}/.config'
    state: directory
    mode: 0700
    owner: '{{ user }}'
    group: '{{ user_group_id }}'

- name: ensure ~/.config/profile.d
  file:
    path: '{{ user_home_dir }}/.config/profile.d'
    state: directory
    mode: 0700
    owner: '{{ user }}'
    group: '{{ user_group_id }}'

- name: qt-scale.sh deployment
  template:
    src: DOTconfig_profile.d_qt-scale.sh.j2
    dest: '{{ user_home_dir }}/.config/profile.d/qt-scale.sh'
    owner: '{{ user }}'
    group: '{{ user_group_id }}'
    mode: 0600
