- name: ~/.ssh
  file:
    path: '{{ user_home_dir }}/.ssh'
    state: directory
    mode: 0700
    owner: '{{ user }}'
    group: '{{ user_group_id }}'

- name: ~/.ssh/config
  template:
    src: DOTssh_config.j2
    dest: '{{ user_home_dir }}/.ssh/config'
    owner: '{{ user }}'
    group: '{{ user_group_id }}'
    mode: 0600
